-- MTEJA AI PostgreSQL schema (multi-tenant)
-- Core tables: organizations, users, customers, conversations, messages,
-- leads, deals, campaigns, ai_agents, integrations, audit_logs
-- All tenant-scoped tables include organization_id with proper indexes
