"""add is_superuser to users

Revision ID: 89ed321bdb9d
Revises: 
Create Date: 2026-09-09 09:14:19.305627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89ed321bdb9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.drop_index(op.f('ix_stock_organization_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.add_column('conversations', sa.Column('external_participant_id', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_conversations_external_participant_id'), 'conversations', ['external_participant_id'], unique=False)
    op.add_column('messages', sa.Column('direction', sa.String(length=10), nullable=False))
    op.add_column('messages', sa.Column('channel', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('messages', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('channel_metadata', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'delivered_at')
    op.drop_column('messages', 'sent_at')
    op.drop_column('messages', 'channel_metadata')
    op.drop_column('messages', 'external_id')
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'channel')
    op.drop_column('messages', 'direction')
    op.drop_index(op.f('ix_conversations_external_participant_id'), table_name='conversations')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'metadata')
    op.drop_column('conversations', 'external_participant_id')
    op.create_table('otp_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('channel', postgresql.ENUM('EMAIL', 'SMS', name='otpchannel'), autoincrement=False, nullable=False),
    sa.Column('purpose', postgresql.ENUM('REGISTRATION', 'LOGIN', 'RESET_PASSWORD', 'SENSITIVE_ACTION', name='otppurpose'), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('otp_codes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_codes_pkey'))
    )
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_index(op.f('ix_otp_codes_id'), 'otp_codes', ['id'], unique=False)
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('class', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('stock_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_pkey'))
    )
    op.create_index(op.f('ix_stock_organization_id'), 'stock', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    # ### end Alembic commands ###
