import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

function TermsOfService({ t }) {
  return (
    <div className="px-6 pt-32 pb-24 max-w-3xl mx-auto">
      <Link
        to="/"
        className="inline-flex items-center gap-1.5 text-sm mb-8 hover:opacity-70 transition-opacity"
        style={{ color: t.muted }}
      >
        <ArrowLeft size={15} /> Back home
      </Link>

      <h1 className="text-3xl font-semibold tracking-tight mb-6" style={{ color: t.text }}>
        Terms of Service
      </h1>

      <div className="space-y-5 text-[15px] leading-relaxed" style={{ color: t.muted }}>
        <p>
          TERMS OF SERVICE

Last Updated: September 7, 2026

Welcome to our Platform Mteja-Ai. These Terms of Service ("Terms") govern your access to and use of our web platform, dashboard, API keys, software, and tools used to build, manage, configure, and deploy autonomous AI agents that interact directly with your end customers via third-party integrations (collectively, the "Service").

Please read these Terms carefully before using the Service. By creating an account, accessing, or using the Service, you ("Client," "User," or "you") agree to be bound by these Terms. If you are entering into these Terms on behalf of a company, startup, or other legal entity, you represent that you have the authority to bind such entity to these Terms.

1. DEFINITIONS
• "AI Agent" means any autonomous or semi-autonomous artificial intelligence model, assistant, or bot generated, prompted, trained, or managed via our Service.
• "Client Data" means all text, instructions, documents, databases, codebase fragments, prompts, or API data uploaded by you to train, condition, or configure the AI Agent.
• "Customer" means your end-users, clients, visitors, or consumers who interact directly with the deployed AI Agent.
• "Output" means the automated text replies, chat messages, answers, decisions, links, or workflow actions generated by the AI Agent and delivered directly to your Customers.
• "Third-Party Integration" means any external communication network, hosting channel, API, marketplace, or software interface (e.g., Slack, WhatsApp, Telegram, Shopify, CRMs) where you deploy the AI Agent.

2. ELIGIBILITY AND ACCOUNT SECURITY
• Age Requirement: You must be at least 18 years old (or the legal age of majority in your jurisdiction) to use this Service.
• Account Management: You are entirely responsible for maintaining the confidentiality of your account credentials, API tokens, and access credentials. You assume full legal responsibility for all activities, billing modifications, and AI agent deployments executed under your account.

3. NATURE OF SERVICE AND AUTOMATED OUTPUTS
• Autonomous Operation: You acknowledge and agree that the core function of the Service is to generate AI Agents capable of messaging and replying directly and autonomously to your Customers without mandatory human oversight or real-time review.
• AI Imperfections and Hallucinations: You explicitly acknowledge that artificial intelligence models are prone to generating unpredictable outputs, including text that may be factual incorrect, unaligned, incomplete, or misleading (commonly referred to as "hallucinations").
• Absolute Client Responsibility: You assume 100% legal, operational, and financial responsibility for configuring, prompting, monitoring, and setting guardrails for your AI Agents. The Company is not responsible or liable for any text, misinformation, bad advice, or legal statements transmitted by your AI Agent to an end-customer.

4. THIRD-PARTY INTEGRATIONS AND PLATFORM DEPENDENCIES
• External Compliance: The Service functions by linking your AI configurations to external Third-Party Integrations. You are solely responsible for ensuring that your automated deployment complies with the terms of service, developer guidelines, and privacy frameworks of those external ecosystems.
• External Actions: We assume no liability for service disruptions, customer communication blocks, API pricing adjustments, or account bans imposed on you or your organization by third-party platforms.

5. INTELLECTUAL PROPERTY RIGHTS
• Platform Ownership: The Company retains all right, title, and interest in and to the Service, including the underlying algorithms, interface designs, infrastructure software, source code, and platform refinements.
• Client Data Ownership: You retain complete ownership of all Client Data uploaded to train the AI. You grant us a limited, worldwide, royalty-free license to host, process, and execute your Client Data strictly to provide, maintain, and optimize the Service for your specific account.
• Allocation of Outputs: To the maximum extent permitted by applicable laws, the Company transfers and assigns to you all intellectual property rights and ownership over the unique text Outputs generated by your customized AI Agents for your Customers.

6. PROHIBITED USES AND SYSTEM RESTRICTIONS
You expressively agree that you will not train, prompt, program, or deploy AI Agents to:
• Generate, transmit, or amplify hate speech, harassment, defamation, explicit content, or dangerous instructions.
• Conduct unauthorized financial manipulation, phishing schemes, legal impersonation of real individuals, or fraudulent multi-level marketing scripts.
• Deploy AI into critical high-risk workflows (such as medical diagnosis, structural engineering calculations, or legal defense representation) where automated errors could cause physical harm or immediate severe financial loss.

7. DISCLAIMER OF WARRANTIES
THE SERVICE IS PROVIDED STRICTLY ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT GUARANTEE THAT THE AUTOMATED OUTPUTS WILL BE 100% ACCURATE, UNINTERRUPTED, SECURE, OR COMPLETELY FREE OF ERRORS.

8. LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS FOUNDERS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF CORPORATE PROFITS, SYSTEMS DATA, REVENUE, CUSTOMER GOODWILL, OR CORPORATE REPUTATION, ARISING OUT OF OR RELATION TO:
1. THE DIRECT AUTOMATED TEXT OUTPUTS, ANSWERS, ERRORS, OR HALLUCINATIONS TRANSMITTED BY THE AI AGENTS.
2. YOUR END CUSTOMERS' EMOTIONAL, PHYSICAL, OR FINANCIAL INTERACTION WITH THE AUTOMATED INTEGRATIONS.
3. SYSTEM REPO DISRUPTIONS CONNECTED TO THIRD-PARTY COMMUNICATION CHANNELS.

IN ALL CIRCUMSTANCES, THE MAXIMUM AGGREGATE LIABILITY OF THE COMPANY SHALL NOT EXCEED THE TOTAL AMOUNT ACTUALLY PAID BY YOU TO THE COMPANY DURING THE PRECEDING TWELVE (12) MONTHS.

9. INDEMNIFICATION
You agree to defend, indemnify, and hold harmless the Company and its representatives from and against any third-party claims, liabilities, losses, administrative fines, or legal expenses (including attorney's fees) arising directly or indirectly from your breach of these Terms, the nature of the Client Data you pass into our systems, or operational claims filed by your Customers regarding replies made by an automated agent.

10. TERMINATION OF ACCESS
We reserve the absolute right to suspend or completely terminate your platform access, invalidate your active API tokens, and pause your active AI Agent integrations instantly without prior warning if you violate these usage restrictions, fail to fulfill subscription payments, or introduce security threats to our multitenant infrastructure.

11. GOVERNING LAW
These Terms shall be interpreted and governed in accordance with local corporate guidelines and applicable international electronic service acts, without regard to conflicting choice of law mechanisms.

        </p>
        <p>
          A real Terms of Service page typically covers: what the service does,
          acceptable use, account responsibilities, payment terms (if
          applicable), limitation of liability, and how disputes are handled.
        </p>
        <p>
          Last updated: 7 september 2026.
        </p>
      </div>
    </div>
  );
}

export default TermsOfService;